### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by becardev** [KeisukeIwabuchi/MQL4-Web#2]
Hello,
I find the principle very nice, but a little problem of understanding on my part.
I want to do a simple get request to understand with the command: Web :: get ("URL", Variable of receive the result);
I have a php file on the remote server with a simple echo "test"; and or echo $_GET['test']; for Web::addParameter("test", "mt4 test"); before request get.
why must we pass a value here: Variable of receive the result?
I don't quite understand how to receive the answer and correct send.

Can you give me this little information?
Thank you

**Comment by KeisukeIwabuchi** [comment]
Hello,

If the addParameter method is not specified, the URL of the first argument of the get method will be accessed as it is.

```
Web :: get ("sample.com", Variable of receive the result); // -> sample.com
```

If you use the addParameter method, it will be accessed with parameters.

```
Web::addParameter("test", "mt4 test");
Web :: get ("sample.com", Variable of receive the result); // sample.com?test=mt4 test
```

You may not need to use the addParamter method for GET.
Mainly used for sending by POST.

**Comment by becardev** [comment]
Thank you for your reply,
sorry but 2021.05.03 15:54:43.833	TestPost NAS100.fs,M15: function is not confirmed  <--- what is error ?
<pre>
<code>
   string url = "http://www.website.com";
   string test;
    Web :: addParameter ("id", "54");

    Web :: get (url, test);
   
    Print (test);

server side -> echo $ _GET ['id'];</code></pre>

**Comment by KeisukeIwabuchi** [comment]
Web.mqh uses the WebRequest function.
To use the WebRequest function, you need to configure MT4.
https://www.mql5.com/en/docs/network
You will need to allow WebRequest and enter the address as shown in the image on this page.

**Comment by becardev** [comment]
Yes i know i use already the same url with webrequest  on tools EA for others app and work without problem.

**Comment by becardev** [comment]
i forget add Request on my controller php app :)

Thanks !

**Comment by KeisukeIwabuchi** [comment]
WebRequest function can be called only from Expert Advisors and scripts.
If you are testing with an indicator, please test with an EA.
